"""Generates the decorative pattern behind the name on the home page.

A scatter of faint points evoking the Galactic population of double white
dwarfs seen edge-on: a thin disc, a central bulge, and a few brighter sources
standing out of the confusion foreground. Decoration only: no axes, no data.

Regenerate with:   python3 _engine/hero-pattern.py > assets/hero-pattern.svg
Standard library only, fixed seed: the output is reproducible.
"""

import math
import random

WIDTH, HEIGHT = 1600, 900
DISC_POINTS = 2200      # faint points of the disc
BULGE_POINTS = 700      # faint points of the bulge
BRIGHT_POINTS = 60      # brighter resolved sources
SEED = 20260914


def clip(value, low, high):
    return max(low, min(high, value))


def main():
    rng = random.Random(SEED)
    cx, cy = WIDTH / 2, HEIGHT / 2
    points = []

    # Disc: exponential profile along the plane, thin vertically, slightly tilted.
    tilt = math.radians(-6)
    for _ in range(DISC_POINTS):
        x = rng.expovariate(1 / 380) * rng.choice((-1, 1))
        y = rng.expovariate(1 / 26) * rng.choice((-1, 1))
        px = cx + x * math.cos(tilt) - y * math.sin(tilt)
        py = cy + x * math.sin(tilt) + y * math.cos(tilt)
        radius = rng.uniform(0.8, 1.8)
        opacity = clip(rng.gauss(0.55, 0.2), 0.15, 0.9)
        points.append((px, py, radius, opacity))

    # Bulge: round, denser, Gaussian.
    for _ in range(BULGE_POINTS):
        px = rng.gauss(cx, 70)
        py = rng.gauss(cy, 55)
        radius = rng.uniform(0.8, 2.0)
        opacity = clip(rng.gauss(0.6, 0.2), 0.15, 0.9)
        points.append((px, py, radius, opacity))

    # Bright sources: scattered, a little larger, drawn last.
    for _ in range(BRIGHT_POINTS):
        px = rng.gauss(cx, 320)
        py = rng.gauss(cy, 120)
        radius = rng.uniform(2.2, 3.6)
        points.append((px, py, radius, 1.0))

    print(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" '
          'preserveAspectRatio="xMidYMid slice" aria-hidden="true" role="img">')
    print("  <!-- Decorative pattern generated by _engine/hero-pattern.py -->")
    print('  <g fill="#ffffff">')
    for px, py, radius, opacity in points:
        if 0 <= px <= WIDTH and 0 <= py <= HEIGHT:
            print(f'    <circle cx="{px:.1f}" cy="{py:.1f}" r="{radius:.1f}" fill-opacity="{opacity:.2f}"/>')
    print("  </g>")
    print("</svg>")


if __name__ == "__main__":
    main()
